### ISSUE TITLE
copy as org-table is not working

### ISSUE THREAD

**Issue by cam-parra** [kyle-west/truthfulness#12]
<img width="915" alt="screen shot 2018-02-21 at 7 17 16 pm" src="https://user-images.githubusercontent.com/9585587/36516582-ecd878bc-173b-11e8-99fb-91773bc6af66.png">

Not sure why it's doing this

**Comment by kyle-west** [comment]
@cam-parra I can't reproduce this. What browser are you using, and can you send me any errors in the console?

**Comment by kyle-west** [comment]
With a little help from Neff, I realized that this bug is a result of the Grammarly plugin for your browser. I will look into mitigating it.

**Comment by kyle-west** [comment]
I hate the solution, but #19 seems to be the only way to disable Grammarly permanently on my page alone.  It should do the trick.
